### ISSUE TITLE
Font Selection

### ISSUE THREAD

**Issue by mervenuryalcin** [app-generator/react-berry-pro#1]
Hi, we purchased Berry Pro recently, and we realised that there are only 3 different fonts on your website. I wonder if I am allowed to use other fonts. And if this is the case, how should our developer team implements it? Is there anything we need to be aware of before starting our project regarding fonts?
Many thanks.

**Comment by codedthemes** [comment]
Of course, you can do it. Berry is not limited to those 3 font families but those are just examples. you need to go to src/config.ts and find 'fontFamily', set your desired font family there. Let me know if that does not work. 

Happy to help!

**Comment by mervenuryalcin** [comment]
Thanks! I assume this is also valid for other styling elements like color, right?

**Comment by codedthemes** [comment]
Yes to some extent. Please check these 'How to' videos. It may help.
https://www.youtube.com/playlist?list=PLknn3jaIuWiALE6UUYYBaefZedx18fN-C

**Comment by app-generator** [comment]
Closing.
